### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/scheme-comparator#1]
- [x] :warning: add message when javascript is disabled
- [x] :eagle: add a spinner during the loading of wasm
- [x] :crossed_fingers: implement xhr POST
- [x] :snail: remove mentions of snabbdom in `main.scm`
- [x] :1st_place_medal: ~improve sxml support (maybe speed it up)~ current seems good enough
- [x] :nail_care: implement style attribute as a JS Object (reactjs really like it like that)
- [x] :nail_care: rename styles properties using dashes (like CSS does and more schemey) and translate to what ReactJS expects e.g. `marginTop`
- [x] :nail_care: add a procedure `merge` that does the equivalent of CSS cascade (!) to be able to "compose" styles: `(merge alist other . rest) -> alist`
- [x] :fireworks: add an animation during xhr calls
- [x] :scream_cat: replace JSON parser with more complete implementation
- [x] :smirk_cat: properly support JSON escape sequence in `sexp->json` in particular line feeds `\n`
- [x] :basecamp: add SRFI-167 and SRFI-168
- [ ] :fire: add support for browser history
  - [ ] :rocket: add support for multiple routes
  - [ ] :first_quarter_moon_with_face:  It should be possible to do a XHR call before the first rendering
  - [ ] :back: Browser back button should work
  - [ ] :zap: add support for pattern as path components
  - [ ] :full_moon_with_face: add support for redirects
- [ ] :scream: debug text input auto-fill behavior in firefox and chromium (possible race condition) :face_with_head_bandage: 
- [ ] :twisted_rightwards_arrows: websocket support
- [ ] :arrow_up: upload support
- [ ] :memo: write documentation in `README.md`
- [ ] :100: add "quote of the day" during the loading of wasm
- [ ] :scroll: bundle libraries + program into a single program
